allowCustomFDP: true
metadata:
  language: http://id.loc.gov/vocabulary/iso639-1/en
  license: http://purl.org/NET/rdflicense/cc-by3.0
fdpConnections:
  - name: 'My local FDP #01 (Albert Einstein)'
    baseURI: http://localhost
    email: albert.einstein@example.com
    password: password
    metadata:
      language: http://id.loc.gov/vocabulary/iso639-1/cs
      publisher: http://publisher2
  - name: 'My local FDP #01 (Nikola Tesla)'
    baseURI: http://localhost
    email: nikola.tesla@example.com
    password: password
    preselected: true
